---
title: "Twitter Trend"
author: "Fabio Votta"
date: "The Date"
output: html_output
---

This script is about:

Analyzing the trend of conspiracy theories

## Packages and Folders

```{r}
# Install these packages if you don't have theme yet
# devtools::install_github("favstats/tidytemplate")
# install.packages("pacman")

pacman::p_load(tidyverse, rtweet)

# Creates folders
# tidytemplate::data_dir()
# tidytemplate::images_dir()
```


## Load Data

```{r, data}
## autheticate via web browser
token <- create_token(
  app = "MyTotallyAwesomeUniqueApp",
  consumer_key = "36CgjeAYngbLqkJqH4rt3Dwna",
  consumer_secret = "vpyPmdTWIWDiexQvLhPvKgVmYChqu0XnJxzGCYqR60QWuypLYG")

## search for 250,000 tweets containing the word data
rt_holohoax3 <- search_tweets(
  "holohoax", n = 250000, retryonratelimit = TRUE, include_rts = T
)

tidytemplate::save_it(rt_holohoax2)
glimpse(rt_holohoax2)

## search for 250,000 tweets containing the word data
rt_qanon <- search_tweets(
  "qanon", n = 250000, retryonratelimit = TRUE, include_rts = T
)

tidytemplate::save_it(rt_qanon)
```


## Analysis / Dataviz

```{r, analysis}

rt_holohoax <- tidytemplate::load_it("data/rt_holohoax.Rdata") %>% 
  rbind(rt_holohoax3) %>% 
  distinct(status_url, .keep_all = T)
  
rt_holohoax_time <- rt_holohoax %>% 
  mutate(year = lubridate::year(created_at)) %>% 
  mutate(day = lubridate::day(created_at)) %>% 
  mutate(month = lubridate::month(created_at)) %>% 
  mutate(cdate = lubridate::ydm(paste0(year, "-", day, "-", month))) %>% 
  group_by(cdate, is_retweet) %>%
  tally() %>% #arrange(cdate)
  ggplot(aes(cdate, n, color = is_retweet)) +
  geom_point(alpha = 0.5) +
  geom_line(alpha = 0.5) +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Number of Tweets mentioning 'Holohoax' in the last 2 Weeks (30.08 - 10.09.2018)",
    subtitle = "Twitter status (tweet) counts aggregated by day",
    caption = "Number of Tweets: 249.\nSource: Data collected from Twitter's REST API via rtweet."
  ) +
  ggthemes::scale_color_fivethirtyeight("Is Retweet?") +
  theme(legend.position = "bottom") +
  scale_x_date(date_breaks = "1 day", date_labels = "%b %d")

tidytemplate::ggsave_it(rt_holohoax_time, width = 10, height = 6)

rt_holohoax %>% 
  arrange(desc(retweet_count))
```

## Q Anon

```{r, analysis}

# rt_holohoax <- tidytemplate::load_it("data/rt_holohoax.Rdata") %>% 
#   rbind(rt_holohoax2) %>% 
#   distinct(status_url, .keep_all = T)
  
rt_qanon_time <- rt_qanon %>% 
  mutate(year = lubridate::year(created_at)) %>% 
  mutate(day = lubridate::day(created_at)) %>% 
  mutate(month = lubridate::month(created_at)) %>% 
  mutate(cdate = lubridate::ydm(paste0(year, "-", day, "-", month))) %>% 
  group_by(cdate, is_retweet) %>%
  tally() %>% #arrange(cdate)
  ggplot(aes(cdate, n, color = is_retweet)) +
  geom_point(alpha = 0.5) +
  geom_line(alpha = 0.5) +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Number of Tweets mentioning 'Holohoax' in the last 2 Weeks (30.08 - 10.09.2018)",
    subtitle = "Twitter status (tweet) counts aggregated by day",
    caption = "Number of Tweets: 235.\nSource: Data collected from Twitter's REST API via rtweet."
  ) +
  ggthemes::scale_color_fivethirtyeight("Is Retweet?") +
  theme(legend.position = "bottom")

tidytemplate::ggsave_it(rt_holohoax_time, width = 10, height = 6)
```


## Analysis / Dataviz

```{r, analysis}

# ts_plot(rt, "1 day") +
  
rt_flatearth %>% 
  mutate(year = lubridate::year(created_at)) %>% 
  mutate(day = lubridate::day(created_at)) %>% 
  mutate(month = lubridate::month(created_at)) %>% 
  mutate(cdate = lubridate::ydm(paste0(year, "-", day, "-", month))) %>% 
  group_by(cdate, is_retweet) %>%
  tally() %>% 
  ggplot(aes(cdate, n, color = is_retweet)) +
  geom_line() +
  ggplot2::theme_minimal() +
  ggplot2::theme(plot.title = ggplot2::element_text(face = "bold")) +
  ggplot2::labs(
    x = NULL, y = NULL,
    title = "Frequency of #rstats Twitter statuses from past 9 days",
    subtitle = "Twitter status (tweet) counts aggregated using three-hour intervals",
    caption = "\nSource: Data collected from Twitter's REST API via rtweet"
  ) 
```